-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "token" STRING NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Marker" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "latitude" FLOAT8 NOT NULL,
    "longitude" FLOAT8 NOT NULL,
    "marketRate" INT4 NOT NULL,
    "unit" STRING NOT NULL,
    "color" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Marker_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Bank" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "bankName" STRING NOT NULL,
    "branchName" STRING NOT NULL,
    "ifscCode" STRING NOT NULL,

    CONSTRAINT "Bank_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Dataset" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "refNo" STRING NOT NULL,
    "datasetName" STRING NOT NULL,
    "bankName" STRING NOT NULL,
    "branchName" STRING NOT NULL,
    "partyName" STRING NOT NULL,
    "colonyName" STRING NOT NULL,
    "cityVillageName" STRING NOT NULL,
    "latitude" FLOAT8 NOT NULL,
    "longitude" FLOAT8 NOT NULL,
    "marketRate" INT4 NOT NULL,
    "unit" STRING NOT NULL,
    "dateOfValuation" TIMESTAMP(3) NOT NULL,
    "entryBy" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL,
    "remarks" STRING NOT NULL,
    "billId" STRING NOT NULL,
    "dateOfVisit" TIMESTAMP(3) NOT NULL,
    "colorMark" STRING NOT NULL,

    CONSTRAINT "Dataset_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Marker_latitude_key" ON "Marker"("latitude");

-- CreateIndex
CREATE UNIQUE INDEX "Marker_longitude_key" ON "Marker"("longitude");

-- CreateIndex
CREATE UNIQUE INDEX "Bank_ifscCode_key" ON "Bank"("ifscCode");

-- CreateIndex
CREATE UNIQUE INDEX "Dataset_refNo_key" ON "Dataset"("refNo");

-- CreateIndex
CREATE UNIQUE INDEX "Dataset_latitude_key" ON "Dataset"("latitude");
